// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoizgemxlmhhzemohkuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvaXpnZW14bG1oaHplbW9oa3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MjA1NzAsImV4cCI6MjA2MzQ5NjU3MH0.7zaCRb22Pi41HNgpVy1lh2WfPtDJH4UDz1EbpTFyTG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);